In [1]:
!pip install pandas numpy matplotlib seaborn scikit-learn

Requirement already satisfied: pandas in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (2.4.3)
Requirement already satisfied: matplotlib in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (3.10.8)
Requirement already satisfied: seaborn in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in C:\Users\hp\OneDrive\Desktop\AIML PROJECT\ash\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:



df1 = pd.read_csv("flight_data_2018_to_2022.csv")
df2 = pd.read_csv("flights_data.csv")

C:\Users\hp\AppData\Local\Temp\ipykernel_21268\1092963325.py:1: DtypeWarning: Columns (0: Originally_Scheduled_Code_Share_Airline, 1: IATA_Code_Originally_Scheduled_Code_Share_Airline, 2: Div1Airport, 3: Div1TailNum, 4: Div2Airport, 5: Div2TailNum) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("flight_data_2018_to_2022.csv")

In [5]:
df1.info()
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 563737 entries, 0 to 563736
Columns: 120 entries, Year to Unnamed: 119
dtypes: float64(72), int64(23), str(25)
memory usage: 516.1 MB
<class 'pandas.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          7500 non-null   int64
 1   flight_date         7500 non-null   str
 2   flight_status       7500 non-null   str
 3   departure_airport   7500 non-null   str
 4   departure_timezone  7500 non-null   str
 5   departure_gate      2850 non-null   str
 6   departure_terminal  5475 non-null   str
 7   arrival_airport     7425 non-null   str
 8   arrival_timezone    7350 non-null   str
 9   arrival_terminal    3975 non-null   str
 10  arrival_gate        225 non-null    str
 11  airline_name        7500 non-null   str
dtypes: int64(1), str(11)
memory usage: 703.3 KB

In [7]:
df1.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,...,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Duplicate,Unnamed: 119
0,2022,1,1,6,4,2022-01-06,DL,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
1,2022,1,1,6,4,2022-01-06,DL,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
2,2022,1,1,6,4,2022-01-06,DL,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
3,2022,1,1,6,4,2022-01-06,DL,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN
4,2022,1,1,6,4,2022-01-06,DL,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN

In [8]:
df2.head()

,Unnamed: 0,flight_date,flight_status,departure_airport,departure_timezone,departure_gate,departure_terminal,arrival_airport,arrival_timezone,arrival_terminal,arrival_gate,airline_name
0,0,2024-09-05,scheduled,Shenzhen,Asia/Shanghai,NaN,T3,Penang International,Asia/Kuala_Lumpur,NaN,NaN,Air China LTD
1,1,2024-09-05,scheduled,Singapore Changi,Asia/Singapore,F52,2,Penang International,Asia/Kuala_Lumpur,NaN,NaN,Virgin Australia
2,2,2024-09-05,scheduled,Singapore Changi,Asia/Singapore,F52,2,Penang International,Asia/Kuala_Lumpur,NaN,NaN,Vistara
3,3,2024-09-05,scheduled,Singapore Changi,Asia/Singapore,F52,2,Penang International,Asia/Kuala_Lumpur,NaN,NaN,United Airlines
4,4,2024-09-05,scheduled,Singapore Changi,Asia/Singapore,F52,2,Penang International,Asia/Kuala_Lumpur,NaN,NaN,Air New Zealand

In [9]:
df=pd.concat([df1,df2])

In [10]:
df.shape

(571237, 132)

In [11]:
df.info()

<class 'pandas.DataFrame'>
Index: 571237 entries, 0 to 7499
Columns: 132 entries, Year to airline_name
dtypes: float64(96), str(36)
memory usage: 579.6 MB

In [18]:
df.isna().sum()

Year                  1
Quarter               1
Month                 1
DayofMonth            1
DayOfWeek             1
                     ..
Flights               1
Distance              1
DistanceGroup         1
DivAirportLandings    1
Duplicate             1
Length: 62, dtype: int64

In [15]:
threshold=len(df)*0.5
df=df.dropna(axis=1,thresh=threshold)

In [17]:
df=df.drop_duplicates()